name: meditra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  http: ^1.2.2  
  intl: ^0.19.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^5.3.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700  
  assets:
    - assets/thym.png
    - assets/gingebre2.jpg
    - assets/prof.jpg
    - assets/pra.png
    - assets/back.png
  
